export const metadata = {
  title: 'We Love Kits | Colombia',
  description: 'Generated by Next.js by Kyonax',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <html lang="es">
      <body>{children}</body>
    </html>
  )
}
