#+TITLE: Image Load Hook
#+AUTHOR: Kyonax - Cristian Moreno
#+auto_tangle: t

The ~Image Load Hook~ is used to import images in the best and lowest version possible, returning a new Image Element.

* Table of Contents :toc:
- [[#useimageload][useImageLoad]]

* useImageLoad
Don't modify this hook if you don't know what to do. (if you can improve the image importing add your code) |

The beginning of the function initialize the different sizes of the website ~sm - md - xl - yl~ and the replace method is giving the file name this will alow us to import the ~webp and avif~ formats of the same picture.

#+BEGIN_SRC typescript :tangle ./hook.tsx
export default function useImageLoad( alt: string, load: boolean, src: string, type: string ) {

    const vw_sizes = { "sm": 365, "md": 768, "xl": 1024, "yl": 1200 };
    let src_name = src.replace(type, '');


    return (
        <>
#+END_SRC

Using HTML I'm creating a template to load Images in the best way possible, using ~picture~ the browser may choose the best option between ~png/jpg, webp, and avif~ depending if the browser support those file extensions. also the ~srcSet~ choose the best file size to load, this depends on wich device is using to load the website ~sm - md - xl yl~.

#+BEGIN_SRC html :tangle ./hook.tsx
            <picture>
              <source
                type="image/avif"
                srcSet={`${src_name}_${vw_sizes.sm}.avif ${vw_sizes.sm}w,
                ${src_name}_${vw_sizes.md}.avif ${vw_sizes.md}w,
                ${src_name}_${vw_sizes.xl}.avif ${vw_sizes.xl}w,
                ${src_name}_${vw_sizes.yl}.avif ${vw_sizes.yl}w`}
                />
              <source
                type="image/webp"
                srcSet={`${src_name}_${vw_sizes.sm}.webp ${vw_sizes.sm}w,
                ${src_name}_${vw_sizes.md}.webp ${vw_sizes.md}w,
                ${src_name}_${vw_sizes.xl}.webp ${vw_sizes.xl}w,
                ${src_name}_${vw_sizes.yl}.webp ${vw_sizes.yl}w`}
                />
              <img
                src={src}
                alt={alt}
                sizes={`(max-width: ${vw_sizes.sm}) ${vw_sizes.sm}px,
                (max-width: ${vw_sizes.md}) ${vw_sizes.md}px,
                (max-width: ${vw_sizes.xl}) ${vw_sizes.xl}px,
                ${vw_sizes.yl}px`}
                srcSet={`${src_name}_${vw_sizes.sm}${type} ${vw_sizes.sm}w,
                ${src_name}_${vw_sizes.md}${type} ${vw_sizes.md}w,
                ${src_name}_${vw_sizes.xl}${type} ${vw_sizes.xl}w,
                ${src_name}_${vw_sizes.yl}${type} ${vw_sizes.yl}w`}
                loading={load ? 'eager' : 'lazy'}
                decoding="async"
              />
            </picture>
#+END_SRC

#+BEGIN_SRC typescript :tangle ./hook.tsx
        </>
    )
}
#+END_SRC
